package storage

import (
	"os"
	"testing"
	"time"

	"achievo/internal/models"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// TestStorage_SaveDetectedGame tests saving detected games
func TestStorage_SaveDetectedGame(t *testing.T) {
	uri := "mongodb://localhost:27017"
	if testURI := os.Getenv("TEST_MONGODB_URI"); testURI != "" {
		uri = testURI
	}

	storage, err := New(uri, "achievo_test", 10)
	if err != nil {
		t.Skipf("Skipping test: MongoDB not available: %v", err)
	}
	defer storage.Close()

	game := &models.Game{
		ID:               "test-detected-game",
		Name:             "Detected Game",
		Type:             models.GameTypeNonSteam,
		ExecutablePath:   "/path/to/game.exe",
		ProcessName:      "game.exe",
		InstallDirectory: "/path/to",
		FirstDetected:    time.Now(),
		LastPlayed:       time.Now(),
	}

	if err := storage.SaveDetectedGame(game); err != nil {
		t.Fatalf("SaveDetectedGame failed: %v", err)
	}

	// Verify game was saved
	retrieved, err := storage.GetGame(game.ID)
	if err != nil {
		t.Fatalf("GetGame failed: %v", err)
	}
	if retrieved == nil || retrieved.Name != game.Name {
		t.Fatalf("Game was not saved correctly")
	}
}

// TestStorage_RuleMetadata tests rule metadata operations
func TestStorage_RuleMetadata(t *testing.T) {
	uri := "mongodb://localhost:27017"
	if testURI := os.Getenv("TEST_MONGODB_URI"); testURI != "" {
		uri = testURI
	}

	storage, err := New(uri, "achievo_test", 10)
	if err != nil {
		t.Skipf("Skipping test: MongoDB not available: %v", err)
	}
	defer storage.Close()

	metadata := &models.RuleMetadata{
		ID:              primitive.NewObjectID().Hex(),
		GameID:          "test-game-123",
		RuleFilePath:    "configs/games/auto/game-test.yaml",
		IsAutoGenerated: true,
		IsReviewed:      false,
		GeneratedAt:     time.Now(),
		LastModified:    time.Now(),
	}

	// Test SaveRuleMetadata
	if err := storage.SaveRuleMetadata(metadata); err != nil {
		t.Fatalf("SaveRuleMetadata failed: %v", err)
	}

	// Test GetRuleMetadata
	retrieved, err := storage.GetRuleMetadata(metadata.GameID)
	if err != nil {
		t.Fatalf("GetRuleMetadata failed: %v", err)
	}
	if retrieved == nil || retrieved.GameID != metadata.GameID {
		t.Fatalf("Rule metadata was not saved correctly")
	}

	// Test MarkRuleAsReviewed
	if err := storage.MarkRuleAsReviewed(metadata.GameID); err != nil {
		t.Fatalf("MarkRuleAsReviewed failed: %v", err)
	}

	// Verify reviewed status
	reviewed, err := storage.GetRuleMetadata(metadata.GameID)
	if err != nil {
		t.Fatalf("GetRuleMetadata after review failed: %v", err)
	}
	if reviewed == nil || !reviewed.IsReviewed {
		t.Fatalf("Rule was not marked as reviewed")
	}

	// Test ListAutoGeneratedRules
	rules, err := storage.ListAutoGeneratedRules(false)
	if err != nil {
		t.Fatalf("ListAutoGeneratedRules failed: %v", err)
	}
	if len(rules) == 0 {
		t.Error("Expected at least one auto-generated rule")
	}

	// Test FetchRulesForGame
	fetched, err := storage.FetchRulesForGame(metadata.GameID)
	if err != nil {
		t.Fatalf("FetchRulesForGame failed: %v", err)
	}
	if fetched == nil || fetched.GameID != metadata.GameID {
		t.Fatalf("FetchRulesForGame returned incorrect metadata")
	}
}

