package models

import "time"

// RuleMetadata tracks metadata about rule files
type RuleMetadata struct {
	ID              string    `bson:"_id" json:"id"`
	GameID          string    `bson:"game_id" json:"game_id"`
	RuleFilePath    string    `bson:"rule_file_path" json:"rule_file_path"`
	IsAutoGenerated bool      `bson:"is_auto_generated" json:"is_auto_generated"`
	IsReviewed      bool      `bson:"is_reviewed" json:"is_reviewed"`
	GeneratedAt     time.Time `bson:"generated_at" json:"generated_at"`
	ReviewedAt      time.Time `bson:"reviewed_at,omitempty" json:"reviewed_at,omitempty"`
	LastModified    time.Time `bson:"last_modified" json:"last_modified"`
}

